version: "3"

vars:
  TERRAFORM_SERVICE_NAME: terraform
  LINTER_SERVICE_NAME: tflint

tasks:
  up:
    cmds:
      - if [ ! -f .env ]; then cp .env.example .env; fi
      - lefthook install
      - docker compose up -d
      - task: init

  down:
    cmds:
      - docker compose down --remove-orphans

  destroy:
    deps: [uninstall-pre-commit]
    cmds:
      - docker compose down --rmi all --volumes --remove-orphans

  init:
    cmds:
      - docker compose exec -T {{.TERRAFORM_SERVICE_NAME}} terraform init
      - docker compose exec -T {{.LINTER_SERVICE_NAME}} tflint --init

  lint:
    aliases: [l]
    cmds:
      - docker compose exec -T {{.TERRAFORM_SERVICE_NAME}} terraform fmt -recursive
      - docker compose exec -T {{.TERRAFORM_SERVICE_NAME}} terraform validate
      - docker compose exec -T {{.LINTER_SERVICE_NAME}} tflint --recursive

  plan:
    aliases: [p]
    cmds:
      - docker compose exec -T {{.TERRAFORM_SERVICE_NAME}} terraform plan

  apply:
    aliases: [a]
    cmds:
      - docker compose exec -T {{.TERRAFORM_SERVICE_NAME}} terraform apply

  sh:
    cmds:
      - docker compose exec {{.TERRAFORM_SERVICE_NAME}} ash

  log:
    cmds:
      - docker compose logs
